# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        SOS\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        sos_db_provider:
            entity:
                class: SOSUserBundle:User
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            http_basic: ~
            anonymous:      true
            provider:       sos_db_provider
            form_login:
                login_path: sos_login
                check_path: sos_login_check
                always_use_default_target_path: true
                default_target_path: /profile
            logout:
                path:       sos_logout
                target:     /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /profile
                always_remember_me: true