<?php

namespace SOS\MainBundle\Repository;

/**
 * DaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaysRepository extends \Doctrine\ORM\EntityRepository
{
}
