<?php

namespace SOS\MainBundle\Repository;

/**
 * HoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoursRepository extends \Doctrine\ORM\EntityRepository
{
}
