<?php

namespace SOS\UserBundle\Repository;

/**
 * UserEditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEditRepository extends \Doctrine\ORM\EntityRepository
{
}
